require File.dirname(__FILE__) + "/dsl/numerical_string"
require File.dirname(__FILE__) + "/callweaver/ogi_server"
#require File.dirname(__FILE__) + "/asterisk/manager_interface"
require File.dirname(__FILE__) + "/callweaver/manager_interface"
require File.dirname(__FILE__) + "/callweaver/commands"
